/** MOCK / DEMONSTRAÇÃO. Substituir estes registros pelo catálogo aprovado antes de publicar comercialmente. */
export const company = {
  name: 'JNG Operadora de Turismo',
  city: 'Osório',
  state: 'RS',
  since: 2004,
  whatsapp: null,
  phone: null,
  email: null,
  streetAddress: null,
  social: [],
  cnpj: null,
};
export const destinations = [
  'Osório',
  'Porto Alegre',
  'Torres',
  'Gramado',
  'Canela',
  'Caxias do Sul',
  'Florianópolis',
  'Balneário Camboriú',
];
export const demo = true;
export const events = [
  {
    id: 'e1',
    slug: 'uma-noite-de-musica',
    title: 'Uma noite de música.',
    subtitle: 'O encontro começa na estrada.',
    category: 'Shows',
    city: 'Porto Alegre',
    venue: 'Local a confirmar',
    date: '2026-10-17T19:00:00-03:00',
    endDate: '2026-10-18T02:00:00-03:00',
    departureLocation: 'Osório · ponto a confirmar',
    departure: '16:00',
    returnTime: 'Após o evento',
    price: null,
    seatsAvailable: null,
    status: 'available',
    featured: true,
    priority: true,
    image: '/assets/event-stage.png',
    poster: '/assets/event-stage.png',
    route: 'Osório → Porto Alegre',
    vehicle: 'Transporte a confirmar',
    included: ['Transporte de ida e volta no roteiro'],
    policies:
      'Ingresso, condições de pagamento e cancelamento dependem da confirmação da operação.',
    demo: true,
  },
  {
    id: 'e2',
    slug: 'encontro-na-serra',
    title: 'Um encontro na serra',
    subtitle: 'Um dia para sair da rotina.',
    category: 'Turismo',
    city: 'Gramado',
    venue: 'Programação a confirmar',
    date: '2026-11-14T09:00:00-03:00',
    endDate: '2026-11-14T22:00:00-03:00',
    departureLocation: 'Osório · ponto a confirmar',
    departure: '06:00',
    returnTime: '20:00 · previsão',
    price: null,
    seatsAvailable: null,
    status: 'coming-soon',
    featured: false,
    image: '/assets/gramado.jpg',
    poster: '/assets/gramado.jpg',
    route: 'Osório → Gramado',
    vehicle: 'Transporte a confirmar',
    included: ['Roteiro de ida e volta'],
    policies: 'A programação final e os itens inclusos serão definidos pela equipe.',
    demo: true,
  },
  {
    id: 'e3',
    slug: 'encontro-no-litoral',
    title: 'Um dia de litoral',
    subtitle: 'Mais horizonte. Mais boas histórias.',
    category: 'Praia',
    city: 'Torres',
    venue: 'Ponto a confirmar',
    date: '2026-12-05T08:00:00-03:00',
    endDate: '2026-12-05T19:00:00-03:00',
    departureLocation: 'Osório · ponto a confirmar',
    departure: '07:00',
    returnTime: '18:00 · previsão',
    price: null,
    seatsAvailable: null,
    status: 'sold-out',
    featured: false,
    image: '/assets/torres.jpg',
    poster: '/assets/torres.jpg',
    route: 'Osório → Torres',
    vehicle: 'Transporte a confirmar',
    included: ['Transporte no roteiro'],
    policies: 'Consulte a equipe sobre novas vagas.',
    demo: true,
  },
];
export const trips = [
  {
    id: 't1',
    slug: 'osorio-gramado',
    title: 'A serra tem outro ritmo.',
    origin: 'Osório',
    destination: 'Gramado',
    departureDate: '2026-11-14',
    returnDate: '2026-11-14',
    departure: '06:00',
    returnTime: '20:00',
    image: '/assets/gramado.jpg',
    price: null,
    availableSeats: null,
    duration: '1 dia',
    category: 'Serra',
    stops: ['Osório · embarque a confirmar', 'Gramado · programação livre'],
    included: ['Roteiro de ida e volta'],
    demo: true,
  },
  {
    id: 't2',
    slug: 'osorio-torres',
    title: 'Seu próximo horizonte.',
    origin: 'Osório',
    destination: 'Torres',
    departureDate: '2026-12-12',
    returnDate: '2026-12-12',
    departure: '07:00',
    returnTime: '18:00',
    image: '/assets/torres.jpg',
    price: null,
    availableSeats: null,
    duration: '1 dia',
    category: 'Praia',
    stops: ['Osório · embarque a confirmar', 'Torres · ponto a confirmar'],
    included: ['Roteiro de ida e volta'],
    demo: true,
  },
  {
    id: 't3',
    slug: 'osorio-florianopolis',
    title: 'Dias leves na ilha.',
    origin: 'Osório',
    destination: 'Florianópolis',
    departureDate: '2027-01-16',
    returnDate: '2027-01-17',
    departure: '05:00',
    returnTime: '18:00',
    image: '/assets/florianopolis.jpg',
    price: null,
    availableSeats: null,
    duration: '2 dias',
    category: 'Turismo',
    stops: [
      'Osório · embarque a confirmar',
      'Parada de apoio · a definir',
      'Florianópolis · chegada',
    ],
    included: ['Roteiro de ida e volta'],
    demo: true,
  },
];
export const routes = [
  {
    id: 'r1',
    origin: 'Osório',
    destination: 'Porto Alegre',
    description: 'Da nossa cidade à capital.',
    x: 26,
    y: 75,
  },
  {
    id: 'r2',
    origin: 'Osório',
    destination: 'Gramado',
    description: 'Novos encontros pela serra.',
    x: 30,
    y: 46,
  },
  {
    id: 'r3',
    origin: 'Osório',
    destination: 'Torres',
    description: 'O litoral no seu caminho.',
    x: 65,
    y: 50,
  },
  {
    id: 'r4',
    origin: 'Osório',
    destination: 'Florianópolis',
    description: 'Uma viagem para mudar de ares.',
    x: 78,
    y: 27,
  },
  {
    id: 'r5',
    origin: 'Osório',
    destination: 'Balneário Camboriú',
    description: 'Mais motivos para reunir o grupo.',
    x: 70,
    y: 10,
  },
];
export const fleet = [
  {
    id: 'f1',
    name: 'Ônibus de turismo',
    category: 'Ônibus',
    image: '/assets/road-hero.png',
    capacity: null,
    amenities: [],
    use: 'Excursões, eventos e grupos',
    demo: true,
  },
  {
    id: 'f2',
    name: 'Micro-ônibus',
    category: 'Micro-ônibus',
    image: '/assets/road-hero.png',
    capacity: null,
    amenities: [],
    use: 'Grupos e deslocamentos regionais',
    demo: true,
  },
  {
    id: 'f3',
    name: 'Van executiva',
    category: 'Van',
    image: '/assets/road-hero.png',
    capacity: null,
    amenities: [],
    use: 'Transfers e pequenos grupos',
    demo: true,
  },
];
export const socials = [
  { id: 's1', title: 'O caminho também faz parte.', image: '/assets/road-hero.png' },
  { id: 's2', title: 'Uma pausa na serra.', image: '/assets/gramado.jpg' },
  { id: 's3', title: 'Colecionando horizontes.', image: '/assets/torres.jpg' },
];
export const testimonials = []; // Somente avaliações reais, autorizadas, devem ser cadastradas.
export const pillars = [
  { icon: 'shield', title: 'Segurança', text: 'Cuidado em cada etapa do caminho.' },
  { icon: 'road', title: 'Experiência', text: 'Uma história na estrada desde 2004.' },
  { icon: 'heart', title: 'Acolhimento', text: 'Pessoas em primeiro lugar, do início ao fim.' },
  { icon: 'arrow', title: 'Movimento', text: 'Novos destinos. Novas histórias para contar.' },
];
export const faq = [
  {
    q: 'Como solicitar um orçamento?',
    a: 'Informe destino, datas e tamanho do grupo no formulário. Revise os detalhes e confirme as condições com a equipe.',
  },
  {
    q: 'Posso planejar uma viagem para meu grupo?',
    a: 'Sim. O formulário permite organizar viagens de grupos, empresas, excursões e eventos para futura análise da equipe.',
  },
  {
    q: 'Como funciona o embarque?',
    a: 'O ponto, o horário e as orientações devem ser confirmados pela equipe antes da viagem.',
  },
  {
    q: 'O transporte inclui o ingresso do evento?',
    a: 'Depende da operação. Consulte os itens inclusos e confirme com a equipe.',
  },
  {
    q: 'Como acompanho as próximas viagens?',
    a: 'As páginas Viagens e Eventos reúnem a programação. Consulte os detalhes e a disponibilidade com a equipe.',
  },
];
export const serviceTypes = [
  'Excursão',
  'Evento',
  'Empresa',
  'Grupo',
  'Transfer',
  'Escolar',
  'Outro',
];
